using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace KerbinMaps.Ksp
{
    /* Guarda en los .cfg lo que se ha cambiado en el editor de edificios.

       No se reescribe el fichero entero desde lo leído (se perderían comentarios, orden y
       lo que KK no entiende pero otro mod sí): se localiza el nodo en el texto y se tocan
       solo sus líneas «clave = valor», se quita su bloque o se añade uno. Los edificios
       nuevos van donde los pone KK, en KerbalKonstructs/NewInstances/<modelo>-instances.cfg,
       y los grupos nuevos en KK_GroupCenter_<cuerpo>_<grupo>.cfg.

       Antes de tocar un fichero se copia a la carpeta de copias, con su ruta dentro de
       GameData. Si el fichero ha cambiado en disco desde que se leyó (KSP abierto y KK
       guardando, por ejemplo), no se toca. */
    public static class KonstructsWriter
    {
        static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        public sealed class Resultado
        {
            public int Ficheros, Instancias, Grupos;
            public readonly List<string> Errores = new();
            public string Copias;
        }

        /* Un nodo en el texto: nombre, dónde empieza su cabecera, su «{» y su «}». */
        public sealed class Span
        {
            public string Name;
            public int Depth, HeaderStart, Open, Close;
            public Span Parent;
        }

        public static Resultado Guardar(KkDatabase db, string carpetaCopias, DateTime leidoEn)
        {
            var res = new Resultado { Copias = Path.Combine(carpetaCopias, DateTime.Now.ToString("yyyyMMdd-HHmmss")) };
            string nuevas = Path.Combine(db.GameData, "KerbalKonstructs", "NewInstances");

            // grupos nuevos o cambiados
            foreach (var g in db.Groups.Values.Where(g => g.Cambiado && !g.Builtin && !g.Implicit).ToList())
            {
                try
                {
                    if (g.CfgPath == null)
                    {
                        Directory.CreateDirectory(nuevas);
                        string f = Path.Combine(nuevas, "KK_GroupCenter_" + Seguro(g.Body + "_" + g.Name) + ".cfg");
                        if (File.Exists(f)) f = Path.Combine(nuevas, "KK_GroupCenter_" + Seguro(g.Body + "_" + g.Name) + "_" + Guid.NewGuid().ToString("N")[..8] + ".cfg");
                        File.WriteAllText(f, "// Generated by Kerbal Konstructs\r\n\r\nKK_GroupCenter\r\n{\r\n" + GrupoValores(g) + "}\r\n");
                        g.CfgPath = f;
                    }
                    else
                    {
                        string text = Leer(g.CfgPath, leidoEn, res);
                        if (text == null) continue;
                        var span = Nodos(text).FirstOrDefault(n => n.Name == "KK_GroupCenter" && n.Depth == 0 &&
                                                                   Valor(text, n, "Group") == g.Name);
                        if (span == null) { res.Errores.Add(Path.GetFileName(g.CfgPath) + ": no encuentro el grupo " + g.Name); continue; }
                        text = PonerValores(text, span, new Dictionary<string, string>
                        {
                            ["RefLatitude"] = N(g.Lat), ["RefLongitude"] = N(g.Lon), ["Heading"] = N(g.Heading),
                            ["RadiusOffset"] = N(g.RadiusOffset),
                        });
                        Escribir(db, g.CfgPath, text, res);
                    }
                    g.Cambiado = g.Nuevo = false;
                    res.Grupos++;
                }
                catch (Exception ex) { res.Errores.Add(g.Name + ": " + ex.Message); }
            }

            // cambios y borrados en ficheros que ya existen, fichero a fichero
            foreach (var porFichero in db.Instances.Where(i => !i.Nuevo && (i.Cambiado || i.Borrado) && i.CfgPath != null).GroupBy(i => i.CfgPath).ToList())
            {
                string path = porFichero.Key;
                try
                {
                    string text = Leer(path, leidoEn, res);
                    if (text == null) continue;
                    var todos = Nodos(text).Where(n => n.Name == "Instances" && n.Parent?.Name == "STATIC").ToList();
                    // de atrás adelante, para que los cambios no muevan lo que falta por tocar
                    var ops = new List<(Span S, KkInstance I)>();
                    foreach (var i in porFichero)
                    {
                        var s = (i.Uuid != null ? todos.FirstOrDefault(n => Valor(text, n, "UUID") == i.Uuid) : null)
                                ?? (i.FileIndex >= 0 && i.FileIndex < todos.Count ? todos[i.FileIndex] : null);
                        if (s == null) { res.Errores.Add(Path.GetFileName(path) + ": no encuentro " + i.Model); continue; }
                        ops.Add((s, i));
                    }
                    foreach (var (s, i) in ops.OrderByDescending(o => o.S.Open))
                    {
                        if (i.Borrado) text = Quitar(text, s);
                        else
                        {
                            var v = InstanciaValores(i);
                            if (i.Uuid == null) { i.Uuid = Guid.NewGuid().ToString(); v["UUID"] = i.Uuid; }
                            text = PonerValores(text, s, v);
                        }
                        res.Instancias++;
                    }
                    Escribir(db, path, text, res);
                    foreach (var (_, i) in ops) i.Cambiado = false;
                }
                catch (Exception ex) { res.Errores.Add(Path.GetFileName(path) + ": " + ex.Message); }
            }

            // edificios nuevos, a NewInstances como hace KK
            foreach (var porModelo in db.Instances.Where(i => i.Nuevo && !i.Borrado).GroupBy(i => i.Model).ToList())
            {
                try
                {
                    Directory.CreateDirectory(nuevas);
                    string path = Path.Combine(nuevas, Seguro(porModelo.Key) + "-instances.cfg");
                    var bloques = new StringBuilder();
                    foreach (var i in porModelo) bloques.Append(Bloque(i, "\t"));
                    string text;
                    if (File.Exists(path))
                    {
                        text = Leer(path, leidoEn, res, nuevo: true);
                        if (text == null) continue;
                        var st = Nodos(text).FirstOrDefault(n => n.Name == "STATIC" && n.Depth == 0 &&
                                                                 (Valor(text, n, "pointername") == porModelo.Key));
                        text = st != null
                            ? text.Insert(st.Close, bloques.ToString())
                            : text + "\r\nSTATIC\r\n{\r\n\tpointername = " + porModelo.Key + "\r\n" + bloques + "}\r\n";
                    }
                    else
                        text = "// Generated by Kerbal Konstructs\r\n\r\nSTATIC\r\n{\r\n\tpointername = " + porModelo.Key + "\r\n" + bloques + "}\r\n";
                    Escribir(db, path, text, res);
                    foreach (var i in porModelo) { i.Nuevo = i.Cambiado = false; i.CfgPath = path; }
                    res.Instancias += porModelo.Count();
                }
                catch (Exception ex) { res.Errores.Add(porModelo.Key + ": " + ex.Message); }
            }
            return res;
        }

        public static bool HayCambios(KkDatabase db) =>
            db != null && (db.Instances.Any(i => i.Cambiado || i.Borrado || i.Nuevo) || db.Groups.Values.Any(g => g.Cambiado && !g.Builtin));

        static string Leer(string path, DateTime leidoEn, Resultado res, bool nuevo = false)
        {
            if (!nuevo && File.GetLastWriteTimeUtc(path) > leidoEn)
            {
                res.Errores.Add(Path.GetFileName(path) + ": ha cambiado en disco desde que se leyó (¿KSP abierto?). Vuelve a leer y repite.");
                return null;
            }
            return File.ReadAllText(path);
        }

        static void Escribir(KkDatabase db, string path, string text, Resultado res)
        {
            if (File.Exists(path))
            {
                string rel = Path.GetRelativePath(db.GameData, path);
                string copia = Path.Combine(res.Copias, rel);
                if (!File.Exists(copia))
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(copia));
                    File.Copy(path, copia);
                }
            }
            File.WriteAllText(path, text);
            res.Ficheros++;
        }

        /* ------------------------------------------------ el texto de los nodos */

        static Dictionary<string, string> InstanciaValores(KkInstance i) => new()
        {
            ["RelativePosition"] = V(i.Rel),
            ["Orientation"] = V(i.Euler),
            ["ModelScale"] = N(i.Scale),
            ["Group"] = i.Group,
        };

        static string Bloque(KkInstance i, string ind) =>
            ind + "Instances\r\n" + ind + "{\r\n" +
            ind + "\tUUID = " + i.Uuid + "\r\n" +
            ind + "\tCelestialBody = " + i.Body + "\r\n" +
            ind + "\tRelativePosition = " + V(i.Rel) + "\r\n" +
            ind + "\tOrientation = " + V(i.Euler) + "\r\n" +
            ind + "\tisScanable = False\r\n" +
            ind + "\tModelScale = " + N(i.Scale) + "\r\n" +
            ind + "\tVisibilityRange = " + N(i.Visibility) + "\r\n" +
            ind + "\tGroup = " + i.Group + "\r\n" +
            ind + "}\r\n";

        static string GrupoValores(KkGroup g) =>
            "\tGroup = " + g.Name + "\r\n" +
            "\tCelestialBody = " + g.Body + "\r\n" +
            "\tOrientation = 0,1,0\r\n" +
            "\tRadiusOffset = " + N(g.RadiusOffset) + "\r\n" +
            "\tHeading = " + N(g.Heading) + "\r\n" +
            "\tModelScale = " + N(g.Scale) + "\r\n" +
            "\tSeaLevelAsReference = " + (g.SeaLevel ? "True" : "False") + "\r\n" +
            "\tRefLatitude = " + N(g.Lat) + "\r\n" +
            "\tRefLongitude = " + N(g.Lon) + "\r\n";

        // décimas de milímetro y de milésima de grado sobran; así no salen cosas como 1E-11
        static string N(double v) => Math.Round(v, 5).ToString("R", Inv);
        static string V(double[] v) => N(v[0]) + "," + N(v[1]) + "," + N(v[2]);
        static string Seguro(string s) => string.Concat(s.Select(c => Path.GetInvalidFileNameChars().Contains(c) ? '_' : c));

        /* Los nodos del texto, con la misma gramática que ConfigNode: el nombre es lo
           último que había antes de la llave y no era «clave = valor». */
        public static List<Span> Nodos(string text)
        {
            var res = new List<Span>();
            var pila = new Stack<Span>();
            int i = 0, n = text.Length;
            int lineaIni = 0;
            string pend = null;
            int pendIni = 0, segIni = 0;
            var seg = new StringBuilder();
            while (i < n)
            {
                char c = text[i];
                if (c == '/' && i + 1 < n && text[i + 1] == '/')
                {
                    while (i < n && text[i] != '\n') i++;
                    continue;
                }
                if (c == '\n')
                {
                    Cerrar();
                    i++;
                    lineaIni = i;
                    continue;
                }
                if (c == '{')
                {
                    Cerrar();
                    var s = new Span { Name = pend ?? "", Depth = pila.Count, HeaderStart = pend != null ? pendIni : lineaIni, Open = i, Parent = pila.Count > 0 ? pila.Peek() : null };
                    pila.Push(s);
                    res.Add(s);
                    pend = null;
                    i++;
                    continue;
                }
                if (c == '}')
                {
                    Cerrar();
                    if (pila.Count > 0) pila.Pop().Close = i;
                    pend = null;
                    i++;
                    continue;
                }
                // la sangría no cuenta: el segmento empieza en su primer carácter visible
                if (seg.Length == 0 && char.IsWhiteSpace(c)) { i++; continue; }
                if (seg.Length == 0) segIni = i;
                seg.Append(c);
                i++;
            }
            return res.Where(s => s.Close > s.Open).ToList();

            void Cerrar()
            {
                string t = seg.ToString().Trim();
                if (t.Length > 0)
                {
                    if (t.Contains('=')) pend = null;
                    else { pend = t; pendIni = LineaDe(segIni); }
                }
                seg.Clear();
            }
            int LineaDe(int pos)
            {
                int p = pos;
                while (p > 0 && text[p - 1] != '\n') p--;
                return p;
            }
        }

        /* Las líneas «clave = valor» que son del propio nodo (no de sus hijos). */
        static IEnumerable<(int Ini, int Fin, string Clave, string Valor)> Lineas(string text, Span s)
        {
            int prof = 0;
            int i = s.Open + 1;
            while (i < s.Close)
            {
                int fin = text.IndexOf('\n', i);
                if (fin < 0 || fin > s.Close) fin = s.Close;
                string linea = text.Substring(i, fin - i);
                string sin = linea;
                int com = sin.IndexOf("//", StringComparison.Ordinal);
                if (com >= 0) sin = sin.Substring(0, com);
                if (prof == 0 && !sin.Contains('{') && !sin.Contains('}'))
                {
                    int eq = sin.IndexOf('=');
                    if (eq > 0) yield return (i, fin, sin.Substring(0, eq).Trim(), sin.Substring(eq + 1).Trim());
                }
                prof += sin.Count(ch => ch == '{') - sin.Count(ch => ch == '}');
                i = fin + 1;
            }
        }

        public static string Valor(string text, Span s, string clave) =>
            Lineas(text, s).Where(l => l.Clave == clave).Select(l => l.Valor).FirstOrDefault();

        /* Cambia o añade valores del nodo, respetando la sangría de sus líneas. */
        public static string PonerValores(string text, Span s, IDictionary<string, string> valores)
        {
            var lineas = Lineas(text, s).ToList();
            string ind = "\t\t";
            if (lineas.Count > 0)
            {
                var l0 = text.Substring(lineas[0].Ini, lineas[0].Fin - lineas[0].Ini);
                ind = l0.Substring(0, l0.Length - l0.TrimStart().Length);
            }
            var faltan = new List<string>();
            var cambios = new List<(int Ini, int Fin, string Nuevo)>();
            foreach (var (k, v) in valores)
            {
                var l = lineas.FirstOrDefault(x => x.Clave == k);
                if (l.Clave == null) { faltan.Add(ind + k + " = " + v); continue; }
                string actual = text.Substring(l.Ini, l.Fin - l.Ini);
                int eq = actual.IndexOf('=');
                string cr = actual.EndsWith("\r") ? "\r" : "";
                cambios.Add((l.Ini, l.Fin, actual.Substring(0, eq + 1) + " " + v + cr));
            }
            foreach (var (ini, fin, nuevo) in cambios.OrderByDescending(c => c.Ini))
                text = text.Substring(0, ini) + nuevo + text.Substring(fin);
            if (faltan.Count > 0)
            {
                // tras la línea de la llave que abre
                int tras = text.IndexOf('\n', s.Open);
                if (tras < 0) tras = s.Open;
                text = text.Insert(tras + 1, string.Join("\r\n", faltan) + "\r\n");
            }
            return text;
        }

        /* Quita el nodo entero, desde su cabecera hasta la llave que lo cierra. */
        public static string Quitar(string text, Span s)
        {
            int fin = s.Close + 1;
            while (fin < text.Length && (text[fin] == ' ' || text[fin] == '\t')) fin++;
            if (fin < text.Length && text[fin] == '\r') fin++;
            if (fin < text.Length && text[fin] == '\n') fin++;
            return text.Substring(0, s.HeaderStart) + text.Substring(fin);
        }
    }
}
